runtime: java11
env_variables:
  MYSQL_HOST: "35.243.221.27"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "xEo;NP^xjL.<SEqm"
  BOT_TOKEN: "5252956900:AAHoHCzSUpRH6ZLJ8M8kK8OvODMcrNZF5-o"
  ACCOUNTS_HOST: ""
  EXCHANGE_HOST: ""
  FRONTEND_HOST: ""
  QA_HOST: ""
instance_class: F1
env: standard
entrypoint: java -jar target/crypto-bot-0.0.1-SNAPSHOT.jar
basic_scaling:
  max_instances: 1
  idle_timeout: 10m