openapi: 3.0.3
info:
  title: CryptoBot - Messaging
  description: API encargada de las comunicaciónes entre los demás componentes del CryptoBot y los usuarios a través de Telegram o Correo electrónico
  version: 0.2.0
paths:
  /messaging/message/diffuse:
    post:
      tags:
        - Messages
      summary: Diffuse a message to the client users
      description: Enabled Endpoint for diffusing messages to the client users. Only available for the admin user.sql.
      requestBody:
        description: diffusion message
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Diffusion'
        required: true
      responses:
        '200':
          description: Diffusion sent
        '500':
          description: Internal error sending diffusion
  /messaging/message/send:
    post:
      tags:
        - Messages
      summary: Send message to a user.sql
      description: Enabled enpoint to send a message to a specified user.sql
      requestBody:
        description: body for sending a message
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SingleMessage'
        required: true
      responses:
        '200':
          description: Message sent successfully
        '500':
          description: Internal error sending message
  /messaging/account/event:
    post:
      tags:
        - Consumers
      summary: New account event
      description: Endpoint for processing account events.
      requestBody:
        description: PubSub Event notification body. The data field comes encrypted in base64
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountPubSubEvent'
        required: true

      responses:
        '200':
          description: account saved/deleted/edited
        '208':
          description: account already exists
        '500':
          description: Error saving/editing/deleting account
components:
  schemas:
    SingleMessage:
      type: object
      properties:
        chat_id:
          type: integer
          example: 1801261524
        message:
          type: string
          example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sagittis hendrerit facilisis. Aenean sit amet arcu nec urna laoreet vehicula nec eget est. Phasellus velit eros, tincidunt vitae magna ac, sagittis auctor massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus porttitor non mi eget posuere."
    Diffusion:
      type: object
      properties:
        title:
          type: string
          example: "Nuevos cambios en el cryptobot"
        body:
          type: string
          example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sagittis hendrerit facilisis. Aenean sit amet arcu nec urna laoreet vehicula nec eget est. Phasellus velit eros, tincidunt vitae magna ac, sagittis auctor massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus porttitor non mi eget posuere."
        image_link:
          type: string
          example: "https://universoabiertoblog.files.wordpress.com/2017/01/aco_bot.jpg"
    AccountPubSubEvent:
      type: object
      properties:
        message:
          type: object
          properties:
            data:
              type: object
              properties:
                telegram_user_id:
                  type: integer
                  example: 1801261524
                operation_type:
                  type: string
                  example: "create/delete/edit"
                first_name:
                  type: string
                  example: "Juan"
                last_name:
                  type: string
                  example: "Perez"
                email:
                  type: string
                  example: "example@gmail.com"
                username:
                  type: string
                  example: "juanpe"

            message_id:
              type: string
              example: "23523146"
